# This is a basic workflow to help you get started with Actions

name: Auto send Info

# Controls when the workflow will run
on:
  # Triggers the workflow at 15:30 Everyday
  schedule:
    - cron: '30 15 * * *' # 每天UTC时间的15:30执行脚本

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
   send_webhook:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Send webhook
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          python send_webhook.py ${{ secrets.WEBHOOK_URL }}

